### ISSUE TITLE
Monthly Distributions

### ISSUE THREAD

**Issue by kchezik** [kchezik/River-Network-Flow-Trends#10]
Hey Sean,

I've plotted the simulated intercept distributions by month for minimum flows as you can see below. The way our code is designed the intercept distributions centre on zero. If I'm understanding things properly this is because the simulated time series don't have a trend and therefore on average the slope coefficients should also exhibit no slope or vertical shifts away from zero. This then suggests that our 'real' intercepts are largely quite different from what we might expect if the trends were due to random draws. Also, our intercepts shouldn't be influenced by the slope because you centred the Area variable in the final gls model. Am I interpreting this correctly? 

The red line is the 'real' intercept value and the black line just makes clear where zero lies.

![intercepts](https://cloud.githubusercontent.com/assets/7605206/9590792/beaab42e-4feb-11e5-8417-3d9f5c0693d2.png)

**Comment by kchezik** [comment]
The exponent variable looks as it should and is a surprisingly strong signal for attenuation.

![exp](https://cloud.githubusercontent.com/assets/7605206/9593093/3f3112ec-4fff-11e5-8cf8-41acf711e124.png)

**Comment by seananderson** [comment]
Good to see this working.

Yes, to the questions in your first post. The intercept is the expected
value at the mean(sqrt(area)) because of the centering and should be
relatively independent of the slope. The question is whether it makes more
sense to just look at the mean of the entire dataset of slopes, perhaps
with the inverse variance weighted mean.

**Comment by kchezik** [comment]
I'm not sure if I'm following you here. I honestly hadn't given much thought to the slope coefficient. As I think about it I'm not really sure what the slope in the final model means? I get that we interpret them as the % decadal change per unit increase in watershed area but what that means in terms of this study I don't know if it has any value. Actually, our hypothesis is that trends attenuate with watershed area. An extreme form of this hypothesis would be to say that no trend is to be expected among sites. I suppose these findings suggest that the basin is shifting for some of these variables despite the buffering of the network (at least for some months per the slope coef. p-values).

Were you thinking that we assume the slope is the mean of the entire dataset or are you talking about aggregating the data and comparing a single simulated distribution against the distribution of monthly estimates? I guess I'm a bit lost with the question you are asking.

**Comment by seananderson** [comment]
I think we're just getting confused by the two kinds of slopes here. There are the slopes from the first set of models and then there is the slope of slopes in the final model.  I was just talking about what you did, which is the mean or intercept in the final model, which represents the mean or intercept of the slopes from the first set of models.

I was just wondering whether you want to use the bootstrap method as you did in the first figure in this thread or to just use the inverse-variance-weighted mean of the first level slopes. I don't think we have to use the bootstrap method in that case because the area doesn't come into play.

**Comment by kchezik** [comment]
I think I understand what you're saying now. Maybe we just look at the distribution of slopes from the individual sites, lets say for example July, and just see if the mean is different from zero? We could do that I suppose. The only thing is that I was planning on plotting attenuation curves from one month representing each season so we have on column of intercepts, one of exponents and then four vertical plots representing the seasons. I guess too me it just seems we should be consistent. I don't know. Which do you prefer?

**Comment by seananderson** [comment]
Yeah, that's fine for consistency. Go ahead as it is.
