### ISSUE TITLE
Funnel_plot: log transformed ratio?

### ISSUE THREAD

**Issue by kchezik** [kchezik/River-Network-Flow-Trends#5]
Hey Sean,

Noticed that the function you developed for the funnel_plot log transforms the ratio. Since it's a ratio do we really need to log transform it? If we don't those data that appear out of place disappear.

Just want to make sure I'm not missing something.

~Kyle
![screen shot 2015-07-07 at 11 41 39 am](https://cloud.githubusercontent.com/assets/7605206/8554189/29dd09ce-249d-11e5-8b28-ba93111b42a7.png)

**Comment by kchezik** [comment]
Actually, it doesn't go away entirely but it looks a bit better. 

We then just appear to need to exp() the upper and lowers to get them in the right spot.

**Comment by seananderson** [comment]
Logging a ratio distributes it between negative infinity and positive infinity and centered on zero. Otherwise the bounds are 0 to 1 and 1 to infinity. Hence, we often work with log ratios and they're usually easiest to visually interpret when logged. The idea was to log-distribute them but label them with the actual ratios, which is what the `scale_y_continuous` is doing.

**Comment by kchezik** [comment]
I see. I'll revert things.
