### ISSUE TITLE
Visualization Options

### ISSUE THREAD

**Issue by kchezik** [kchezik/River-Network-Flow-Trends#6]
Hey Sean,

I was thinking something like this for the funnel plot. I haven't completed it but figured I'd get your thoughts. The lines are coloured by month and try to link warming months such as Feb. to Jul with colours going from yellow to red while cooling months such as Aug. to Jan. go from orange to blue. The width of the line is dependant on the steepness of the Exp variable for that month. The points are coloured by there extremeness from 1 in either the increasing (blues) or declining (reds) directions. I'm aiming to show that water months exhibit the attenuation more than cooler months with 'hotter' thicker lines getting narrower with area than 'cooler' , thinner lines.

![rplot](https://cloud.githubusercontent.com/assets/7605206/8560438/8bd339c6-24cc-11e5-8bc2-aad8fc38e7b5.png)

**Comment by seananderson** [comment]
Cool! I think in general we should probably limit the number of different scales on the same figure. Especially when there are multiple dimensions showing the same thing. I might just use the colour scale for the lines and either give the dots the same colours as their month or make the dots some shade of grey. And try without varying the widths of the lines. That pattern is cool though... it inspired me to finally crack out Stan and try fitting the gls model there. Turned out to be really simple. And it gets you nice posteriors on all the parameters, including the varexp parameter. These are the posteriors of that parameter ordered from January onwards:

![screenshot of r 2015-07-07 6 55 26 pm](https://cloud.githubusercontent.com/assets/19349/8561437/66ef6478-24da-11e5-8904-27f65f814667.png)

If we want to focus on that pattern, then perhaps we could do something with a plot like that. (making them little beanplots or dots and lines)

With a couple extra lines of code we could incorporate the uncertainty around the rates too so that uncertainty is propagated from the GAMs into the GLS model.

Here's the entirety of the code I wrote for that:

```R
stan_model <-
'data {
  int<lower=0> N; // rows of data
  vector[N] y; // vector to hold (log) ratios
  vector[N] area; // vector to hold (transformed) area
}
parameters {
  real mu; // mean
  real<lower=0> sigma; // residual standard deviation
  real varexp; // varExp exponent
}
model {
  mu ~ normal(0, 5);
  varexp ~ normal(0, 2.5);
  sigma ~ cauchy(0, 2.5);
  for (i in 1:N) {
    y[i] ~ normal(mu, sqrt(pow(sigma, 2) * exp(2 * area[i] * varexp)));
  }
}
'

library(rstan)
sm <- stan_model(model_code = stan_model)

out <- plyr::dlply(dat, "nMonth", function(d) {
  s <- sampling(sm,
    data = list(N = nrow(d), y = log(d$ratio), area = sqrt(d$Area) / 100),
    iter = 2000, chains = 4, warmup = 1000,
    pars = c("mu", "varexp", "sigma"))
  s
})

par(mfrow = c(12, 1), cex = 0.6, mar = c(1, 1, 1, 1))
plyr::l_ply(out, function(x) {
  plot(density(extract(x)$varexp), xlim = c(-1.1, 0.1), main = "", )
})

# testing:
# d <- filter(dat, nMonth == 2)
# library(nlme)
#m <- gls(log(ratio)~1, weights = varExp(form = ~(sqrt(Area) / sd(sqrt(Area)))), data = d)
```

**Comment by kchezik** [comment]
This is really cool! I think it would be interesting to investigate the uncertainty in the GAM and just see it's effect on the posteriors of the GLS parameters. I assume this will be computationally sort of expensive?

I'm not sure I'm visualizing your bean plot idea. So the concept being that we discuss the rate of attenuation by area for each month and how they differ among months. Other than having some idea of how months differ from one another, how is this different from the plot we already have? 

Maybe we could incorporate this into the plot we have? Each line would be a density distribution such that the most likely exp parameter value is dark and it gets lighter out to lets say 2sd. If we do this for each line with the right colours it could lead to a cool effect where an overall annual value becomes apparent among the monthly values. Sort of artistic but could be really cool.

**Comment by kchezik** [comment]
Okay, I've played around with the plot I sent you earlier and while I didn't follow your advice a whole bunch I think I did it for good reason. First, the grey is ugly as F#$*. Second, I think we loose something that could be intuitively grasped by having the points on a colour scale. We could group the months by site so all points from a site take on a single colour that relates to that sites extreme difference from 1?

Secondly, I tried making the lines all the same thickness but again I think the relationship I want to draw attention to becomes muddled without it. I want the red to stand out because it's attenuation is stronger.

Finally, it would only take two general legends to describe all the scale relationships.

Here's the plot:

![rplot](https://cloud.githubusercontent.com/assets/7605206/8579148/c257a964-2567-11e5-9b62-768b6efbb7cd.png)

**Comment by kchezik** [comment]
By the way, did you look at the mu posteriors? It's interesting how no month is predominately over zero.

Also, why are the posteriors so narrow? Given the ratios by month plot I would expect them to be wider. Do you think if we add the variation in the GAMs into the Stan model they'll become less certain? 

![rplot](https://cloud.githubusercontent.com/assets/7605206/8581933/b4b218c4-2578-11e5-9347-2b1c16f7c80c.png)

**Comment by seananderson** [comment]
We've come so far since this issue thread :)
